# SPRING SECURITY - OAUTH2
# CLIENT ID, CLIENT SECRET
# GOOGLE
spring:
  security:
    oauth2:
      client:
        registration:
          # GOOGLE
          google:
            client-id: 370272984771-vb7c047faamqm7etmrekk4kpeerbqerc.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          # NAVER
          naver:
            client-id: r7eLYhYj_c6FCrlF_ghM
            client-secret: yETFgqpJAp
            scope:
              - email
              - name
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response