create table MEMBER_TABLE(
	id bigint generated by default as identity,
	name varchar(255) NOT NULL,
	email varchar(255) NOT NULL,
	password varchar(255) NOT NULL,
	primary key(id)
);

CREATE TABLE BOARD_TABLE(
	id bigint generated by default as identity,
	title varchar(31) NOT NULL,
	contents varchar(999999) NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP(0) NOT NULL,
	views bigint DEFAULT 0 NOT NULL,
	member_id bigint,

	primary key(id),
	foreign key(member_id) references MEMBER_TABLE(id) on delete cascade
)

create table ROLE_TABLE(
	id bigint generated by default as identity,
	member_id bigint,
	role varchar(10) default('MEMBER')

	constraint check_role check role in ('MEMBER', 'ADMIN'),
	primary key(id),
	foreign key(member_id) references MEMBER_TABLE(id) on delete cascade
)

create table FILE_TABLE(
	id bigint generated by default as identity,
	board_id bigint,
	originalFilename varchar(255) NOT NULL,
	currentFilename varchar(255) NOT NULL,

	primary key(id),
	foreign key(board_id) references BOARD_TABLE(id) on delete cascade
)

create table LIKES_TABLE(
	id bigint generated by default as identity,
	member_id bigint,
	board_id bigint,

	primary key(id),
	foreign key(member_id) references MEMBER_TABLE(id) on delete cascade,
	foreign key(board_id) references BOARD_TABLE(id) on delete cascade,
	unique(member_id, board_id)
)

create table COMMENT_TABLE(
	id bigint generated by default as identity,
	parent_id bigint DEFAULT NULL,
	member_id bigint,
	board_id bigint,
	comments varchar(255) NOT NULL,
	created_at timestamp DEFAULT CURRENT_TIMESTAMP(0),

	primary key(id),
	foreign key(parent_id) references COMMENT_TABLE(id) on delete cascade,
	foreign key(member_id) references MEMBER_TABLE(id) on delete cascade,
	foreign key(board_id) references BOARD_TABLE(id) on delete cascade
)